### PR TITLE
Fix formatting in Links, Tips, and Picks from Episode 001. Closes #62

### LINKED ISSUE #62: Bad formatting in Episode 001's Links, Tips, and Picks
Just wondering if [this](https://github.com/javascriptair/site/blob/master/episodes/2015-12-16/index.js#L20) formatting of two Markdown links is intentional. Looks like this on the site:

screen shot 2016-03-16 at 4 15 27 pm

### PR DESCRIPTION
**Pull request by sotojuan**

### CODE REVIEW

File: episodes/2015-12-16/index.js [hunk 1]
```diff
@@ -17,7 +17,8 @@ export default {
       ],
       picks: [
         `[Javascript Allonge](https://leanpub.com/javascript-allonge)`,
-        `[Hello Declarative World!](http://codon.com/hello-declarative-world)[my ES6 implementation](https://github.com/ashleygwilliams/relational-node)`,
+        `[Hello Declarative World!](http://codon.com/hello-declarative-world)`,
```
Comment (kentcdodds) [inline episodes/2015-12-16/index.js:20]: Actually, I think these are related and should be on one line. Just needs to have a separator. Maybe `-`?

Comment (kentcdodds) [inline episodes/2015-12-16/index.js:20]: Actually, nevermind. I think it's good!

**Comment by kentcdodds** [comment]
Thanks!
